### ISSUE TITLE
webpack version

### ISSUE THREAD

**Issue by Cucak** [MetaMask/React-MetaMask-Login-Button#1]
Hey could you update and fix this issue with webpack, cant run my project because of webpack conflict. 
![image](https://user-images.githubusercontent.com/19273055/78385674-8736ec80-75dc-11ea-8b88-ea3569c1274e.png)
Thank you!

**Comment by whymarrh** [comment]
We recommend using the [Ethereum provider](https://docs.metamask.io/guide/ethereum-provider.html) directly (& [our onboarding library](https://docs.metamask.io/guide/onboarding-library.html), if desired) instead of this button.

**Comment by whymarrh** [comment]
(Also you can use [Rimble](https://rimble.consensys.design) directly, which is what this button used.)
